### PR TITLE
refactor: switch to gov account

### PR DESCRIPTION
**Pull request by jmgilman**
Moves CI to use resources from the gov AWS account.

### CODE REVIEW

**Comment by minikin** [comment]
@stevenj @const-iohk Can you have a look, please?

**Comment by jmgilman** [comment]
The last merge broke a ton of the Nix builds.

**Comment by minikin** [comment]
@jmgilman I'm sorry. I have no idea why 🤨

**Comment by minikin** [comment]
And many Nix things are broken in the `main` too.

**Comment by jmgilman** [comment]
@minikin #212 needs to be reverted. I had @cameron1024 restore the branch, and I'll try and see why it broke things a bit later.

**Review by const-iohk — APPROVED** [review]
This all seems OK. Pinning the exact versions, replacing quotations, and switching from vit to gov account. Approved.

**Pull request merged**
