### PR TITLE
feat: Update cat-data-service API

### PR DESCRIPTION
**Pull request by Mr-Leshiy**
# Description

Slightly modify cat-data-service API, to be more clear and understandable

### CODE REVIEW

**Review by saibatizoku — APPROVED** [review]
LGTM.

**Review by FelipeRosa — APPROVED** [review]
LGTM

**Comment by minikin** [comment]
Various typos in `core_backend_api.yaml`:
- [Contiunous](https://github.com/input-output-hk/catalyst-core/blob/f5ee4056cb3cb712eb05a132fe9fcfd148030025/book/src/07_web_api/openapi/core_backend_api.yaml#L52)
- [Catalsyt](https://github.com/input-output-hk/catalyst-core/blob/f5ee4056cb3cb712eb05a132fe9fcfd148030025/book/src/07_web_api/openapi/core_backend_api.yaml#L113)
- [occured](https://github.com/input-output-hk/catalyst-core/blob/f5ee4056cb3cb712eb05a132fe9fcfd148030025/book/src/07_web_api/openapi/core_backend_api.yaml#L336)
- [chronolgically](https://github.com/input-output-hk/catalyst-core/blob/f5ee4056cb3cb712eb05a132fe9fcfd148030025/book/src/07_web_api/openapi/core_backend_api.yaml#L556)
- [ommitted](https://github.com/input-output-hk/catalyst-core/blob/f5ee4056cb3cb712eb05a132fe9fcfd148030025/book/src/07_web_api/openapi/core_backend_api.yaml#L568)
- [Detaild](https://github.com/input-output-hk/catalyst-core/blob/f5ee4056cb3cb712eb05a132fe9fcfd148030025/book/src/07_web_api/openapi/core_backend_api.yaml#L617)
- [Distribuition](https://github.com/input-output-hk/catalyst-core/blob/f5ee4056cb3cb712eb05a132fe9fcfd148030025/book/src/07_web_api/openapi/core_backend_api.yaml#L818)
- [propsal](https://github.com/input-output-hk/catalyst-core/blob/f5ee4056cb3cb712eb05a132fe9fcfd148030025/book/src/07_web_api/openapi/core_backend_api.yaml#L934)
- [propsals](https://github.com/input-output-hk/catalyst-core/blob/f5ee4056cb3cb712eb05a132fe9fcfd148030025/book/src/07_web_api/openapi/core_backend_api.yaml#L937)
- [choise](https://github.com/input-output-hk/catalyst-core/blob/f5ee4056cb3cb712eb05a132fe9fcfd148030025/book/src/07_web_api/openapi/core_backend_api.yaml#L940)
- [posssible](https://github.com/input-output-hk/catalyst-core/blob/f5ee4056cb3cb712eb05a132fe9fcfd148030025/book/src/07_web_api/openapi/core_backend_api.yaml#L1031)
- [posssible](https://github.com/input-output-hk/catalyst-core/blob/f5ee4056cb3cb712eb05a132fe9fcfd148030025/book/src/07_web_api/openapi/core_backend_api.yaml#L1039)

**Comment by Mr-Leshiy** [comment]
@minikin Do you think we should remove it from them ? For me personally it is a good reminder what should be implemented and what missed and will show for others who will read this doc what we are going to have in this service

**Comment by minikin** [comment]
@Mr-Leshiy, we should remove them and create Jira tickets for each item. I'll add tickets in Jira.

**Pull request merged**
