### PR TITLE
Refactor and speed up ci tests

### PR DESCRIPTION
**Pull request by kukkok3**
Refactor/speed up CI tests:

- [x] Have a job build and cache all the dependecies:

  -  Use Swatinem/rust-cache@v2 to cache all the Rust files and dependencies
  -  Use `nextest --archive` option to cache nextest files and dependencies
  -  Use actions/cache/save@v3 to cache external dependencies builds (vit-ss,jormungandr etc)

 Note that Rust files are only cached on merge to `main `as cache data created in a pull-request-triggered CI run can't be seen by other PRs. Instead nextest archive and external dependencies are rebuild at each run, cached to be passed to the matrix of runners and then cleaned up. For this untill this PR is merged not all the cache will hit. On my fork, when all cache hits the total running time is about 35min
- [x] Use `matrix` with `nextest --partition` command to run the tests accross different runners.
- [x] Make coverage and clippy job use the same cache as cargo build
- [x] Add integration tests
- [x] Divide building tests and dependecies in two different runners

Future work:

- Pick the slowest tests and reduce their running time
- Dont rebuild deps if is not necessary
- Add remaining tests and features

### CODE REVIEW

**Comment by dkijania** [comment]
nice!

**Review by Mr-Leshiy — DISMISSED** [review]

**Comment by minikin** [comment]
@Mr-Leshiy this pr is tagged as `do not merge` and `do not review` :)

**Comment by saibatizoku** [comment]
@kukkok3 do you think that `.github/workflows/ci-tests-n-coverage.yml` can be included in this PR?

**Comment by kukkok3** [comment]
> @kukkok3 do you think that `.github/workflows/ci-tests-n-coverage.yml` can be included in this PR?

Yes it would make sense, should I update it?

**Review by saibatizoku — APPROVED** [review]
Awesome!

**Pull request merged**
