### PR TITLE
Add Cargo manifest for monorepo

### PR DESCRIPTION
**Pull request by saibatizoku**
* Creates top-level Cargo.toml that declares a workspace
* Moves workspace members into top-level
  * Most of the profile settings for legacy workspaces are put into the individual crates in their manifest, and at the moment are being ignored by Cargo.
  * Removes legacy workspaces by removing the Cargo manifest that defines them.

- [X] Still needs some cleanup of inner Cargo.lock files

### CODE REVIEW

**Review by cameron1024 — APPROVED** [review]
Looks good to me, but probably want to wait for other team members to have a look before merging

**Comment by cameron1024** [comment]
I guess we also want to think about how this impacts the nix build. IIRC some of the crates have their own workspace-aware nix build scripts, and we probably don't want to break those

**Comment by saibatizoku** [comment]
> I guess we also want to think about how this impacts the nix build. IIRC some of the crates have their own workspace-aware nix build scripts, and we probably don't want to break those

Yeah, I'm doing it because the nix flakes were having problems, mainly (e.g. flake file needs to be on same directory as Cargo.lock). I guess that the next step is to refactor nix for the monorepo.

**Comment by cong-or** [comment]
LGTM

**Comment by garbas** [comment]
> > I guess we also want to think about how this impacts the nix build. IIRC some of the crates have their own workspace-aware nix build scripts, and we probably don't want to break those
> 
> Yeah, I'm doing it because the nix flakes were having problems, mainly (e.g. flake file needs to be on same directory as Cargo.lock). I guess that the next step is to refactor nix for the monorepo.

Correct, this will make nix packaging much easier.

**Review by Mr-Leshiy — APPROVED** [review]

**Pull request merged**
