### PR TITLE
fix: Snapshot-changes

### PR DESCRIPTION
**Pull request by cong-or**
Fix snapshot to match and improve upon legacy haskell tool output.

### CODE REVIEW

**Comment by stevenj** [comment]
Something still being detected as wrong when it doesn't look wrong.
Snapshot from preprod @ slot 
```json
 {
    "spec_61284": "a119ef64a50185825820564a23c021456b6199a2f9637bfb58fb78a3aa0e4fd79f1195bfc18edd7177ab14825820579f1647fa50e875892eceeea8185b72fd928d7492273e2784cf524035e0e77e148258205b8a3febe76ddd739e3b9d17a17eaf00d869c71a4af4803769d8c15cc9f41dff14825820ad42cd20764ebc3934ba29e8d217f093fa20b390055c00b1bfbfe0948614daa114825820ae18794e19a8e45ce1b432f9fd7cfb5505bec18ae3c041a8d848cd4e087572ba14025820d2a3100e28cb40130630631eb58837703643afb0a090d29a564f5b8f7147e5fd0358390086210f0402ce6264c8c74106910e7dba4bf35ef4b9180f056bc6f56a2b9936fb5ec237bb3bd964fb836714c12030352f05a914786c9c3634041a00d8fe9f0500",
    "spec_61285": "a119ef65a1015840ea608730bffbd30df1fd0f3957f984737a6fbbedb11995c5a026567b8d8c8e5317263a4baad414d784b427e52c8109430cc66a7bb08acd1a7f0849238aba5304",
    "registration": null,
    "errors": [
      {
        "CborDeserializationFailed": {
          "err": "Failed to deserialize Registration CBOR: Invalid address prefix Invalid rewards address: address prefix is: \"0\"\n the first hex char should be in the range\n\n                0x0? - 0x7? or 0xE? , 0xF?\n\n                followed by 0 or 1 which defines the network id"
        }
      }
    ]
  },
```

Decoding gives:
```json
{61284: {1: [[h'564A23C021456B6199A2F9637BFB58FB78A3AA0E4FD79F1195BFC18EDD7177AB', 20], [h'579F1647FA50E875892ECEEEA8185B72FD928D7492273E2784CF524035E0E77E', 20], [h'5B8A3FEBE76DDD739E3B9D17A17EAF00D869C71A4AF4803769D8C15CC9F41DFF', 20], [h'AD42CD20764EBC3934BA29E8D217F093FA20B390055C00B1BFBFE0948614DAA1', 20], [h'AE18794E19A8E45CE1B432F9FD7CFB5505BEC18AE3C041A8D848CD4E087572BA', 20]], 2: h'D2A3100E28CB40130630631EB58837703643AFB0A090D29A564F5B8F7147E5FD', 3: h'0086210F0402CE6264C8C74106910E7DBA4BF35EF4B9180F056BC6F56A2B9936FB5EC237BB3BD964FB836714C12030352F05A914786C9C3634', 4: 14220959, 5: 0}}
```

The rewards address is type 0x0 on network 0x0 (preprod) which is correct.
Its also 57 bytes long which is correct.  I don't think it should have errored.

**Comment by stevenj** [comment]
The `*.no_stake.json` should be renamed to `*.unregistered.json`  so its clear what it is.
Its current contents are only the stake addresses that are not registered, but we need their staked ada as well.
This is important so we can show an unregistered voter how much voting power they have before they register.

```json
[
  "e0a0c75371014330950cc758f973dee61e411018da3da67250bf38b467",
  "e0901340ce9ebd469f88f70d640cd62666d2e70a3280ecb1571bf678dd",
  "e0ba1c8f8836ef828ee6705e49fc9cbc743f101c3fa071346c04426028",
  "e0ccd10d00d2e4922e66c52113384445235731ea5b357a90036060d506"
]
```

should be

```json
{
  "e0a0c75371014330950cc758f973dee61e411018da3da67250bf38b467": 12345,
  "e0901340ce9ebd469f88f70d640cd62666d2e70a3280ecb1571bf678dd": 6789,
  "e0ba1c8f8836ef828ee6705e49fc9cbc743f101c3fa071346c04426028": 0,
  "e0ccd10d00d2e4922e66c52113384445235731ea5b357a90036060d506": 10203484756
}
```

**Comment by cong-or** [comment]
> Something still being detected as wrong when it doesn't look wrong. Snapshot from preprod @ slot 26523318
> 
> Example error:
> 
> ```json
>  {
>     "spec_61284": "a119ef64a50185825820564a23c021456b6199a2f9637bfb58fb78a3aa0e4fd79f1195bfc18edd7177ab14825820579f1647fa50e875892eceeea8185b72fd928d7492273e2784cf524035e0e77e148258205b8a3febe76ddd739e3b9d17a17eaf00d869c71a4af4803769d8c15cc9f41dff14825820ad42cd20764ebc3934ba29e8d217f093fa20b390055c00b1bfbfe0948614daa114825820ae18794e19a8e45ce1b432f9fd7cfb5505bec18ae3c041a8d848cd4e087572ba14025820d2a3100e28cb40130630631eb58837703643afb0a090d29a564f5b8f7147e5fd0358390086210f0402ce6264c8c74106910e7dba4bf35ef4b9180f056bc6f56a2b9936fb5ec237bb3bd964fb836714c12030352f05a914786c9c3634041a00d8fe9f0500",
>     "spec_61285": "a119ef65a1015840ea608730bffbd30df1fd0f3957f984737a6fbbedb11995c5a026567b8d8c8e5317263a4baad414d784b427e52c8109430cc66a7bb08acd1a7f0849238aba5304",
>     "registration": null,
>     "errors": [
>       {
>         "CborDeserializationFailed": {
>           "err": "Failed to deserialize Registration CBOR: Invalid address prefix Invalid rewards address: address prefix is: \"0\"\n the first hex char should be in the range\n\n                0x0? - 0x7? or 0xE? , 0xF?\n\n                followed by 0 or 1 which defines the network id"
>         }
>       }
>     ]
>   },
> ```
> 
> Decoding gives:
> 
> ```json
> {61284: {
>     1: [[h'564A23C021456B6199A2F9637BFB58FB78A3AA0E4FD79F1195BFC18EDD7177AB', 20], [h'579F1647FA50E875892ECEEEA8185B72FD928D7492273E2784CF524035E0E77E', 20], [h'5B8A3FEBE76DDD739E3B9D17A17EAF00D869C71A4AF4803769D8C15CC9F41DFF', 20], [h'AD42CD20764EBC3934BA29E8D217F093FA20B390055C00B1BFBFE0948614DAA1', 20], [h'AE18794E19A8E45CE1B432F9FD7CFB5505BEC18AE3C041A8D848CD4E087572BA', 20]],
>     2: h'D2A3100E28CB40130630631EB58837703643AFB0A090D29A564F5B8F7147E5FD', 
>     3: h'0086210F0402CE6264C8C74106910E7DBA4BF35EF4B9180F056BC6F56A2B9936FB5EC237BB3BD964FB836714C12030352F05A914786C9C3634',
>     4: 14220959, 
>     5: 0
> }}
> ```
> 
> The rewards address is type 0x0 on network 0x0 (preprod) which is correct. Its also 57 bytes long which is correct. I don't think it should have errored.

yes it seems:
0 or 1 are valid addrs in the following cases:
type = 0x0 -  network = 0
type = 0x0 -  network = 1

I have fixed this and added explicit tests.

**Comment by cong-or** [comment]
> The `*.no_stake.json` should be renamed to `*.unregistered.json` so its clear what it is. Its current contents are only the stake addresses that are not registered, but we need their staked ada as well. This is important so we can show an unregistered voter how much voting power they have before they register.
> 
> ```json
> [
>   "e0a0c75371014330950cc758f973dee61e411018da3da67250bf38b467",
>   "e0901340ce9ebd469f88f70d640cd62666d2e70a3280ecb1571bf678dd",
>   "e0ba1c8f8836ef828ee6705e49fc9cbc743f101c3fa071346c04426028",
>   "e0ccd10d00d2e4922e66c52113384445235731ea5b357a90036060d506"
> ]
> ```
> 
> should be
> 
> ```json
> {
>   "e0a0c75371014330950cc758f973dee61e411018da3da67250bf38b467": 12345,
>   "e0901340ce9ebd469f88f70d640cd62666d2e70a3280ecb1571bf678dd": 6789,
>   "e0ba1c8f8836ef828ee6705e49fc9cbc743f101c3fa071346c04426028": 0,
>   "e0ccd10d00d2e4922e66c52113384445235731ea5b357a90036060d506": 10203484756
> }
> ```

should be fixed now.

**Comment by stevenj** [comment]
Also in the errors file:
```json

    "spec_61284": "a119ef64a4015820c5a6f78bc1778e84dbc137bee58f6f143749e0f89527d02d28a72a87d7359f03025820a8f3084b6bd908759ddb91ed8adfbe2101855da975e67552f4a57e8479c3d56003581de13d2cc7fa7be7bacc11b3de9ccae30511e0a8654f4aa45203b25b6f70041a054d09ee",
    "spec_61285": "a119ef65a1015840cc90cd9f0c4e7c5da9c47c22264e6d01f97715cb74c13337932a2919dc520e1907681652991953352cfa42b25decb6fc8bed088f646c6876512058ce39373b09",
```
should have leading `0x` to be consistent with other binary fields.

As should the unregistered file:

```json
  "e12c7a5d4c23cced42a67dc0fb30a98681d82b234cb46b33373ea546ea": 2235300,
  "e193fd5fca05d2401ac97ad5ef64ce307a9e6b292119d806e6d3163a00": 31302474,
```
should be 
``` json
  "0xe12c7a5d4c23cced42a67dc0fb30a98681d82b234cb46b33373ea546ea": 2235300,
  "0xe193fd5fca05d2401ac97ad5ef64ce307a9e6b292119d806e6d3163a00": 31302474,
```

**Review by stevenj — APPROVED** [review]
After extensive testing,  I believe this tool is producing 100% valid results and is picking up errors that the Haskell tool passes.
Thanks to everyone involved.

**Review by stevenj — APPROVED** [review]

**Review by stevenj — APPROVED** [review]

**Pull request merged**
