### PR TITLE
fix: Fix IdeaScale importer bugs | NPG-7381

### PR DESCRIPTION
**Pull request by FelipeRosa**
# Description

- Fixed proposals not being filtered by campaign id when writing them to the DB which was causing an exception
- Fixed campaigns not being found caused by a filter on the campaign name
- Some other minor fixes

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

#### 1. API call to get ideas from a stage that is not part of a funnel of the campaigns in the campaign group:

```
poetry run ideascale-importer ideascale import-all --api-token API_KEY --database-url DBURL --ideascale-api-url https://temp-cardano-sandbox.ideascale.com  --event-id 1 --campaign-group-id 87 --stage-id 1
```

Imported 0 proposals as expected.

#### 2. API call to get ideas from a stage that is part of a funnel of the campaigns in the campaign group:
```
poetry run ideascale-importer ideascale import-all --api-token API_KEY --database-url DBURL --ideascale-api-url https://temp-cardano-sandbox.ideascale.com  --event-id 1 --campaign-group-id 87 --stage-id 4573
```

Imported 2 proposals as expected.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by minikin** [comment]
@FelipeRosa @kukkok3 Should we merge this one?

**Comment by Mr-Leshiy** [comment]
@FelipeRosa @kukkok3 BTW, does this bug exists inside the original ideascale-importer tool ? which we are going to use for the fund10

**Comment by FelipeRosa** [comment]
@Mr-Leshiy I don't think so. These were all specific to the way the new importer is implemented.

**Review by kukkok3 — COMMENTED** [review]
@minikin Since this is post fund10 stuff, is at the bottom of my list at the moment, I'll review it next week

**Review by kukkok3 — APPROVED** [review]
LGTM

**Pull request merged**
