### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by minikin**
- Add CONTRIBUTING.md

### CODE REVIEW

**Review by FelipeRosa — APPROVED** [review]
Are we tracking the TODOs somewhere?

**Review by saibatizoku — APPROVED** [review]
Awesome!

**Comment by minikin** [comment]
@FelipeRosa Right now, only on our Confluence and meeting notes. What would be your suggestion to track TODOs?

**Comment by FelipeRosa** [comment]
> Confluence and meeting notes. What would be your suggestion to track TODOs?

@minikin thanks for the reply. I have nothing specific in mind. Just wanted to know about this.

**Pull request merged**
