### PR TITLE
docs: Add description of the prometheus metrics used in jormungandr | NPG-000

### PR DESCRIPTION
**Pull request by saibatizoku**
# Description

Adds documentation for prometheus metrics.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Mr-Leshiy — APPROVED** [review]
LGTM

**Review by kukkok3 — APPROVED** [review]
LGTM

**Comment by minikin** [comment]
@jmgilman, we need your feedback here, please.

**Comment by minikin** [comment]
resolve https://github.com/input-output-hk/catalyst-world/issues/84

**Review by minikin — APPROVED** [review]

**Pull request merged**
