### PR TITLE
feat: Voting node builds block0

### PR DESCRIPTION
**Pull request by saibatizoku**
Adds a schedule of tasks for Leader0 nodes to self-configure for the next election.

### CODE REVIEW

**Review by stevenj — APPROVED** [review]
Looks OK.
OK to merge into the main feature branch.

**Comment by minikin** [comment]
@saibatizoku

**Comment by saibatizoku** [comment]
I'm updating the queries to include all the fields from the event-db, I'll merge/close this PR as soon as I include those changes. @minikin @stevenj

**Comment by saibatizoku** [comment]
This branch includes other branches that are WIP, I'm cherry-picking the commits into https://github.com/input-output-hk/catalyst-core/tree/feature/voting-node-service and merging with `main`.

**Pull request closed without merging**
