### PR TITLE
Discontinue evm feature

### PR DESCRIPTION
**Pull request by saibatizoku**
This discontinues the `evm` feature available in crates within the workspace. It also removes `chain-evm` from the workspace. The last commit with the crate is stored as the git tag: https://github.com/input-output-hk/catalyst-core/tree/chain-evm-discontinued

This reduces the build time considerably.

### CODE REVIEW

**Review by cameron1024 — DISMISSED** [review]
-7000 lines 🎉 LGTM

**Comment by saibatizoku** [comment]
@jmgilman any idea why the nix CI test for jormungandr is failing?

**Review by minikin — CHANGES_REQUESTED** [review]
@saibatizoku Should we create a tag or branch of the system with the state before evm things were removed 🧐?

**Comment by saibatizoku** [comment]
> @saibatizoku Should we create a tag or branch of the system with the state before evm things were removed monocle_face?

Yeah, @minikin , I added a tag: https://github.com/input-output-hk/catalyst-core/tree/chain-evm-discontinued

**Review by minikin — APPROVED** [review]

**Comment by jmgilman** [comment]
Sorry I missed the ping on this. We [build with prometheus](https://github.com/input-output-hk/catalyst-core/blob/main/nix/jormungandr/packages.nix#L15) by default because we rely on it for metric scraping. It appears something is broken when that feature is enabled.

**Pull request merged**
