### PR TITLE
Change diesel version and remove logic and fixes voting_nodes migration

### PR DESCRIPTION
**Pull request by saibatizoku**
Moves from `diesel_migrations` v2 to v1.4, to keep schemas compatible between Election DB and VitSS tests.
Removes logic from `election-db` crate, leaving just the schema.
Changes primary key type from `NAME` to `VARCHAR`, to get rid of `diesel::sql_types` in schema.

### CODE REVIEW

**Review by Mr-Leshiy — APPROVED** [review]
LGTM

**Comment by stevenj** [comment]
Why do we want to use 1.4 vs 2?
Vit-ss doesn't;t use this crate yet, and when/if it does, we should upgrade vit-ss.

**Comment by minikin** [comment]
@saibatizoku Can we fix conflicts and merge this PR, please?

**Review by stevenj — CHANGES_REQUESTED** [review]
Obsoleted by changes to DB crate.  
I Suggest deleting this PR.

**Comment by saibatizoku** [comment]
Cancelling this, as it's obsolete nowl

**Pull request closed without merging**
