### PR TITLE
chore: update rust-toolchain to 1.71.0 | NPG-0000

### PR DESCRIPTION
**Pull request by minikin**
# Description

Update rust-toolchain to 1.71.0

### CODE REVIEW

**Comment by minikin** [comment]
@stevenj @FelipeRosa @saibatizoku @Mr-Leshiy 
We need to migrate to the latest stable version because we have dependencies in other PR which require a higher version of Rust than we have now. @cong-or and I fixed most of the Clippy issues, but now we have [failing tests](https://github.com/input-output-hk/catalyst-core/actions/runs/5732110519/job/15534405642?pr=495). 
Can someone with more knowledge of falling tests have a look, please?

**Comment by saibatizoku** [comment]
> @stevenj @jmgilman @FelipeRosa @saibatizoku @Mr-Leshiy We need to migrate to the latest stable version because we have dependencies in other PR which require a higher version of Rust than we have now. @cong-or and I fixed most of the Clippy issues, but now we have [failing tests](https://github.com/input-output-hk/catalyst-core/actions/runs/5732110519/job/15534405642?pr=495). Can someone with more knowledge of falling tests have a look, please?
> 
> Moreover, do we actually use vitss in this repo? Vitss tests started to [fail](https://github.com/input-output-hk/catalyst-core/actions/runs/5732110523/job/15534901193?pr=495) too. FYI @kukkok3 @nicopado

@minikin I'm taking a look, running the earthly tests locally.

**Comment by saibatizoku** [comment]
@minikin I couldn't get the tests to work, but I did find that the error is a schema mismatch, such as:

`thread 'queries::registration::tests::get_delegator_test' panicked at 'called `Result::unwrap()` on an `Err` value: MismatchedSchema { was: 9, expected: 10 }', src/event-db/src/queries/registration.rs:429:57`

That's what I was able to find out, but I'm unfamiliar with schema numeration details.

**Comment by stevenj** [comment]
@minikin We do not need or use vit-ss anymore.  Its test can be totally disabled,  pending complete removal at a future date.
We probably need a note in the Readme highlighting that the vit-ss code is deprecated and will be removed in future.  To document why the tests are disabled.
We can also stop it building to save time in CI.

**Review by Mr-Leshiy — APPROVED** [review]
LGTM

**Comment by minikin** [comment]
Thank you, everyone, for your collaboration!

**Pull request merged**
