### PR TITLE
feat(catalyst-toolbox): Adds loadtest snapshot processing feature. | NPG-0000

### PR DESCRIPTION
**Pull request by stevenj**
This change adds the ability to auto-generate snapshot data for automated loadtests from real snapshot data.
It also:
* makes a snapshot artifact file compatible with Vit-SS.
* adds snapshot report and configuration data to the main snapshot file.
* Keeps voters who are underpower, but flags them.
* Sorts both files so they always produce consistent output (helps check for difference run to run).
* Fix consistency with output fields (Hex fields all have "0x" on the front.

All of this was needed for loadtest purposes, which is why its all in the same PR rather than a series of PR's.
This may require some modification to scripts which consume the snapshot report due to the changes.

### CODE REVIEW

**Review by cong-or — APPROVED** [review]
lgtm

**Review by minikin — APPROVED** [review]

**Review by minikin — DISMISSED** [review]

**Review by Mr-Leshiy — APPROVED** [review]
LGTM

**Comment by Mr-Leshiy** [comment]
@stevenj are we going to merge this branch ?

**Review by kukkok3 — DISMISSED** [review]
LGTM

**Review by cong-or — APPROVED** [review]
lgtm

**Pull request merged**
